export const UPDATE_AGE = 'UPDATE_AGE';
export const UPDATE_SEX = 'UPDATE_SEX';
export const UPDATE_HEIGHT = 'UPDATE_HEIGHT';
export const UPDATE_WEIGHT = 'UPDATE_WEIGHT';
export const UPDATE_ACTIVITY_LEVEL = 'UPDATE_ACTIVITY_LEVEL';